export const FirestoreProductSchema = {
  TL: [
    {
      image_src: "1.png",
      image_x: 76,
      image_y: 236,
      image_height: 400,
      tag_x: 356,
      tag_y: 176,
      tag_height: 120,
      text_x: 76,
      text_y: 236,
      text_fontsize: 24,
      title: "Product One",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "2.png",
      image_x: 572,
      image_y: 204,
      image_height: 200,
      tag_x: 692,
      tag_y: 164,
      tag_height: 80,
      text_x: 572,
      text_y: 204,
      text_fontsize: 18,
      title: "Product Two",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "3.png",
      image_x: 572,
      image_y: 468,
      image_height: 200,
      tag_x: 692,
      tag_y: 428,
      tag_height: 80,
      text_x: 572,
      text_y: 468,
      text_fontsize: 18,
      title: "Product Three",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "4.png",
      image_x: 44,
      image_y: 732,
      image_height: 200,
      tag_x: 164,
      tag_y: 692,
      tag_height: 80,
      text_x: 44,
      text_y: 732,
      text_fontsize: 18,
      title: "Product Four",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "5.png",
      image_x: 308,
      image_y: 732,
      image_height: 200,
      tag_x: 428,
      tag_y: 692,
      tag_height: 80,
      text_x: 308,
      text_y: 732,
      text_fontsize: 18,
      title: "Product Five",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "6.png",
      image_x: 572,
      image_y: 732,
      image_height: 200,
      tag_x: 692,
      tag_y: 692,
      tag_height: 80,
      text_x: 572,
      text_y: 732,
      text_fontsize: 18,
      title: "Product Six",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
  ],
  TR: [
    {
      image_src: "1.png",
      image_x: 44,
      image_y: 204,
      image_height: 200,
      tag_x: 164,
      tag_y: 164,
      tag_height: 80,
      text_x: 44,
      text_y: 204,
      text_fontsize: 18,
      title: "Product One",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "2.png",
      image_x: 44,
      image_y: 468,
      image_height: 200,
      tag_x: 164,
      tag_y: 428,
      tag_height: 80,
      text_x: 44,
      text_y: 468,
      text_fontsize: 18,
      title: "Product Two",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "3.png",
      image_x: 340,
      image_y: 236,
      image_height: 400,
      tag_x: 620,
      tag_y: 176,
      tag_height: 120,
      text_x: 340,
      text_y: 236,
      text_fontsize: 24,
      title: "Product Three",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "4.png",
      image_x: 44,
      image_y: 732,
      image_height: 200,
      tag_x: 164,
      tag_y: 692,
      tag_height: 80,
      text_x: 44,
      text_y: 732,
      text_fontsize: 18,
      title: "Product Four",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "5.png",
      image_x: 308,
      image_y: 732,
      image_height: 200,
      tag_x: 428,
      tag_y: 692,
      tag_height: 80,
      text_x: 308,
      text_y: 732,
      text_fontsize: 18,
      title: "Product Five",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
    {
      image_src: "6.png",
      image_x: 572,
      image_y: 732,
      image_height: 200,
      tag_x: 692,
      tag_y: 692,
      tag_height: 80,
      text_x: 572,
      text_y: 732,
      text_fontsize: 18,
      title: "Product Six",
      store: "Store Name",
      link: "https://",
      price: 99,
    },
  ],
};
